name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Workload Identity Federation
      contents: read   # Allows GitHub Actions to read the repo contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/961525812802/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-action-828023681@armortech.iam.gserviceaccount.com"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: armortech

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gemtrakr-service \
            --image us-central1-docker.pkg.dev/armortech/gemtrackr-repo/gemtrakr-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
