name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Workload Identity Federation
      contents: read  # Allows GitHub Actions to read the repo contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Active Account (Before Auth)
        run: gcloud auth list

      - name: Debug GitHub OIDC Token
        run: |
          echo "Running in GitHub Repository: $GITHUB_REPOSITORY"
          echo "GitHub Actor: $GITHUB_ACTOR"
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://iam.googleapis.com" | jq .
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/961525812802/locations/global/workloadIdentityPools/gemtrakr-pool/providers/gemtrakr-provider"
          service_account: "github-action-828023681@armortech.iam.gserviceaccount.com"

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"

      - name: Check Active Account (After Auth)
        run: gcloud auth list

      - name: Configure Credentials
        run: gcloud auth configure-credentials --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_GHA_CREDS_PATH

      - name: Check Active Account (After Activate)
        run: gcloud auth list

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: armortech

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gemtrakr-service \
            --image us-central1-docker.pkg.dev/armortech/gemtrackr-repo/gemtrakr-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated